services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - pgData:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: songs
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d songs" ]
      interval: 3s
      timeout: 5s
      retries: 2
      start_period: 5s

  server:
    build: .
    container_name: server
    ports:
      - "8080:8080"
    command: "./server"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/migrations:/app/db/migrations
      - ./config/:/app/config/
      - ./docs:/app/docs

volumes:
  pgData: