// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "openapi": "3.0.3",
    "info": {
        "title": "Music Library API",
        "description": "API для онлайн библиотеки песен.",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:8080",
            "description": "Local server"
        }
    ],
    "paths": {
		"/info": {
            "get": {
				"summary": "Получить информацию о песне",
                "tags": ["info"],
                "description": "Получение информации о песни по названию и автору",
                "parameters": [
                    {
                        "name": "group",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "song",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/info"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка при получении списка песен",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении списка песен",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/songs": {
            "get": {
                "summary": "Получить список песен",
                "description": "Получение данных библиотеки с возможностью фильтрации по полям и пагинацией. Обязательно заполнить хотя бы 1 поле",
                "tags": ["songs"],
                "parameters": [
                    {
                        "name": "group",
                        "in": "query",
                        "description": "Фильтрация по названию группы",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "song",
                        "in": "query",
                        "description": "Фильтрация по названию песни",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "release_date",
                        "in": "query",
                        "description": "Фильтрация по дате выпуска",
                        "schema": {
                            "type": "string",
                            "format": "date"
                        }
                    },
                    {
                        "name": "page",
                        "in": "query",
                        "description": "Номер страницы",
                        "schema": {
                            "type": "integer",
                            "default": 1
                        }
                    },
                    {
                        "name": "limit",
                        "in": "query",
                        "description": "Количество элементов на странице",
                        "schema": {
                            "type": "integer",
                            "default": 10
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список песен",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Song"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка при получении списка песен",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Добавить новую песню",
                "description": "Добавление новой песни в базу данных.",
                "tags": ["songs"],
                "requestBody": {
                    "description": "Данные новой песни",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/NewSong"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Добавленная песня",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Song"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при добавлении песни",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/songs/{id}": {
            "get": {
                "summary": "Получить песню по ID",
                "description": "Извлечение песни по ее уникальному идентификатору.",
                "tags": ["songs"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о песне",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Song"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Песня не найдена",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "summary": "Обновить песню",
                "description": "Обновление существующей песни по ее ID.",
                "tags": ["songs"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "description": "Обновленные данные песни",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UpdateReq"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Обновленная песня",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UpdatedSong"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Песня не найдена",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Удалить песню",
                "description": "Удаление песни по ее ID.",
                "tags": ["songs"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Песня успешно удалена"
                    },
                    "404": {
                        "description": "Песня не найдена",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при удалении песни",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/songs/{id}/verse": {
            "get": {
                "summary": "Получить куплет песни по ее ID",
                "description": "Извлекает определенный куплет из песни по ее идентификатору. Если параметр verse не указан, будет возвращен первый куплет по умолчанию.",
                "tags": ["songs"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID песни",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "example": 1
                        }
                    },
                    {
                        "name": "verse",
                        "in": "query",
                        "description": "Номер куплета",
                        "required": false,
                        "schema": {
                            "type": "integer",
                            "example": 1
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное извлечение куплета",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "verse": {
                                            "type": "string",
                                            "example": "Ooh baby, don't you know I suffer?"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Неправильное ID песни",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Песня не найдена",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка обработки запроса",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Song": {
                "type": "object",
                "required": ["group", "song"],
                "properties": {
                    "id": {
                        "type": "integer",
                        "example": 1
                    },
                    "group": {
                        "type": "string",
                        "example": "Muse"
                    },
                    "song": {
                        "type": "string",
                        "example": "Supermassive Black Hole"
                    },
                    "releaseDate": {
                        "type": "string",
                        "format": "date",
                        "example": "2006-07-16"
                    },
                    "text": {
                        "type": "string",
                        "example": "Ooh baby, don't you know I suffer?\nOoh baby, can you hear me moan?"
                    },
                    "link": {
                        "type": "string",
                        "example": "https://www.youtube.com/watch?v=Xsp3_a-PMTw"
                    }
                }
            },
			"info": {
                "type": "object",
                "required": ["group", "song"],
                "properties": {
                    "releaseDate": {
                        "type": "string",
                        "format": "date",
                        "example": "1992-09-21"
                    },
                    "text": {
                        "type": "string",
                        "example": "When you were here before\nCouldn't look you in the eye"
                    },
                    "link": {
                        "type": "string",
                        "example": "https://www.youtube.com/watch?v=XFkzRNyygfk"
                    }
                }
            },
			"NewSong": {
                "type": "object",
                "required": ["group", "song"],
                "properties": {
                    "group": {
                        "type": "string",
                        "example": "Muse"
                    },
                    "song": {
                        "type": "string",
                        "example": "Supermassive Black Hole"
                    },
                    "releaseDate": {
                        "type": "string",
                        "format": "date",
                        "example": "2006-07-16"
                    },
                    "text": {
                        "type": "string",
                        "example": "Ooh baby, don't you know I suffer?\nOoh baby, can you hear me moan?"
                    },
                    "link": {
                        "type": "string",
                        "example": "https://www.youtube.com/watch?v=Xsp3_a-PMTw"
                    }
                }
            },
            "UpdateReq": {
                "type": "object",
                "required": ["group", "song"],
                "properties": {
                    "group": {
                        "type": "string",
                        "example": "Radiohead"
                    },
                    "song": {
                        "type": "string",
                        "example": "Creep"
                    },
                    "releaseDate": {
                        "type": "string",
                        "format": "date",
                        "example": "1992-09-21"
                    },
                    "text": {
                        "type": "string",
                        "example": "When you were here before\nCouldn't look you in the eye"
                    },
                    "link": {
                        "type": "string",
                        "example": "https://www.youtube.com/watch?v=XFkzRNyygfk"
                    }
                }
            },
            "UpdatedSong": {
                "type": "object",
                "required": ["group", "song"],
                "properties": {
                    "id": {
                        "type": "integer",
                        "example": 1
                    },
                    "group": {
                        "type": "string",
                        "example": "Radiohead"
                    },
                    "song": {
                        "type": "string",
                        "example": "Creep"
                    },
                    "releaseDate": {
                        "type": "string",
                        "format": "date",
                        "example": "1992-09-21"
                    },
                    "text": {
                        "type": "string",
                        "example": "When you were here before\nCouldn't look you in the eye"
                    },
                    "link": {
                        "type": "string",
                        "example": "https://www.youtube.com/watch?v=XFkzRNyygfk"
                    }
                }
            },
            "Error": {
                "type": "object",
                "properties": {
                    "error": {
                        "type": "string",
                        "example": "Ошибка сервера"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Music Library API",
	Description:      "API для онлайн библиотеки песен.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
